#include <stdio.h>
#include <stdlib.h>    //srand(), rand() 함수 사용을 위한 헤더 파일
#include <time.h>     //time() 함수 사용을 위한 헤더 파일

int main(void)
{
    int answer[4];
    int guess[4];
    int i, j;
    int count = 1;
    int strike;
    int ball;

    srand((unsigned)time(NULL));

    for (i = 0; i < 4; i++)
    {
        int num = 0;
        answer[i] = (rand() % 9 + 1);// 1~9 사이의 난수 생성
        for (j = 0; j < i; j++)
        {
            if (answer[j] == answer[i])//중복되는 수 존재
            {
                num = 1;
                break;
            }
        }
        if (num == 1)
            i--;//중복되는 수 존재로 인해 랜덤 번호 다시 추출
    }

    printf("Welcome to Number Baseball Game!\n");
    printf("Guess the 4-digit number generated by the computer.\n");

    while (1)
    {
        printf("\n[%d Round] Guess the answer : ", count);

        scanf_s("%d%d%d%d", &guess[0], &guess[1], &guess[2], &guess[3]);

        strike = 0;
        ball = 0;

        for (i = 0; i < 4; i++)
        {
            for (j = 0; j < 4; j++)
            {
                if (answer[i] == guess[j]) // 랜덤으로 생성된 4자리 수와 자신이 추측한 4자리 수가 숫자, 위치 모두 일치할 경우
                {
                    if (i == j)
                    {
                        strike++;
                        if (strike == 4)
                        {
                            printf("\n[The final result : %dRound] 4strikes, Game over.\n", count);
                            exit(1);
                        }
                    }
                    else if (i != j) // 랜덤으로 생성된 4자리 수와 자신이 추측한 4자리 수가 숫자는 일치하나 위치가 일치하지 않을 경우
                        ball++;
                }
            }
        }
        printf("[Result]\nStrike : %d, Ball : %d\n\n", strike, ball);
        count++;
    }
    return 0;
}
